#!/bin/bash
set -e

# Disable stock CCID library
if test -e /usr/libexec/SmartCardServices/drivers/ifd-ccid.bundle/Contents/Info.plist; then
  mv /usr/libexec/SmartCardServices/drivers/ifd-ccid.bundle/Contents/Info.plist \
    /usr/libexec/SmartCardServices/drivers/ifd-ccid.bundle/Contents/Info.plist_backup
fi

# force re-load of drivers
killall -QUIT pcscd || true
